---
title: "Lab 2"
format: html
execute:
   echo: false
   warning: false
   fig-dpi: 300
---

```{r}
library(knitr)
```

```{r}
#Choose the maximum number of digits after your decimal in this document
DecimalPlaces = 7
```

```{r}
TransformationTable = data.frame(iris$Sepal.Length)

TransformationTable$Plus3 = TransformationTable[,1] + 3

TransformationTable$DivBy3 = TransformationTable[,1] / 3

TransformationTable$DivBy3Plus5 = (TransformationTable[,1] / 3) + 5

Means = round(colMeans(TransformationTable),2)
Variance = round(apply(TransformationTable,2, var),2)
StdDev = round(apply(TransformationTable,2, sd),2)

TransformationTableResults = rbind(c("Means",Means),
                                   c("Variance",Variance),
                                   c("Std. Dev.",StdDev)
                                   )

kable(TransformationTable, digit = DecimalPlaces)
kable(TransformationTableResults, digit = DecimalPlaces)
```

```{r}
#This line is all you need to generate a boxplot.
boxplot(iris$Sepal.Length)
#########################################


# These are to show you the different ways to calculate the placement of whiskers.
# If you uncomment the second definitions of UpperWhisker and LowerWhisker, then render this document again, you'll see horizontal lines appear at the upper and lower whiskers on your boxplot.
FirstQuart = summary(iris$Sepal.Length)[2]
ThirdQuart = summary(iris$Sepal.Length)[5]
Median = median(iris$Sepal.Length)

Midline = Median
IQR = ThirdQuart - FirstQuart
BoxTop = ThirdQuart
BoxBottom = FirstQuart
UpperWhisker = ThirdQuart + IQR * 1.5
LowerWhisker = FirstQuart - IQR * 1.5
#UpperWhisker = max(iris$Sepal.Length)
#LowerWhisker = min(iris$Sepal.Length)


### These will draw your lines. Don't change them.
abline(h = Midline)
abline(h = BoxTop)
abline(h = BoxBottom)
abline(h = UpperWhisker)
abline(h = LowerWhisker)

summary(iris$Sepal.Length)

```

