---
title: "Lab 1"
format: html
execute:
  echo: false
---
```{r}
library(knitr)
```

```{r}
# Create frequency table for carburetors 0–9, even though some of those numbers
# have zero fequency; i.e., there are no cars with 0 or 5 carburetors. This
# leaves all options open for making a frequency table.
carb = factor(mtcars$carb, levels = 0:9)

# This set of functions gives us the frequency for each level we just made and
# makes the table have the right format for our work.
freq = as.numeric(table(carb))

# This gives us the total number of engines measured.
freq_total = sum(freq)

# Relative frequency is the frequency of a certain value relative to the total.
rel_freq = freq / freq_total

# This function adds in sequence the frequencies we have measured; i.e., the
# number of engines with 0 carbs. plus those with 1, plus those with 2...
cumu_f = cumsum(freq)

# The converts the cumulative fequency to a percentage of the total.
cumu_pct = cumu_f / freq_total * 100

# Build the table. In the data.frame function you write the name of the column,
# then the equal sign, then what you want to go in that column.
tab = data.frame(
  Carburetors = 0:9, # Make a line in the table for each value
  f = freq,
  `Relative f` = round(rel_freq, 2), # Rounds to two decimal places
  `Cumulative f` = cumu_f,
  `Cumulative %` = round(cumu_pct),
  check.names = FALSE
)

# Add Total row
tab = rbind(tab, data.frame(
  Carburetors = "Total",
  f = freq_total,
  `Relative f` = "",
  `Cumulative f` = "",
  `Cumulative %` = "",
  check.names = FALSE
))

# Print the table
kable(tab, row.names = FALSE)
```


```{r}
#Set a serifed font
par(family = "serif")

# This version of the variable carbs will give you no gaps in your histogram and
# only show you categories which are populated.
carbNoGaps = factor(carb)


# Create the histogram using the barplot function. This relies on the frequency
# table we just made.
bp = barplot(table(carbNoGaps),
            space = 0,         # Changes from a barplot to a Histogram
            col = "white",     # Leaves no bar fill for a minimalist printing
            ylab = "Frequency",
            xlab = "Number of Carburetors",
            cex.lab = 1.3,    # Sets the font of the axis labels to be larger
            main = "",        # Stops the default label from being printed
            cex.names = 1,    # Optional: size axis labels: 1 is no change.
            cex.axis = 1,     # Optional: size axis numbers.
            yaxs = 'i',       # Tightens the axis to the plot.
            xaxs = 'i',
            mgp = c(2.2, 0.5, 0)  # Changes the margins around the plot;
                                  # see par(); c(axis title, axis labels and axis line)
            
            )

#Restore default font
par(family = "")
```


```{r}
# Set a serifed font
par(family = "serif")

# Bin the carburetor values into three groups: 1-3, 4-6, and 7-9
carbBinned = cut(mtcars$carb,
                  breaks = c(0, 3, 6, 9),
                  labels = c("1-3", "4-6", "7-9"))

# Create the barplot (now truly histogram-like with bins)
bp = barplot(table(carbBinned),
             space = 0,           # Changes from a barplot to a Histogram
             col = "white",       # Leaves no bar fill for a minimalist printing
             ylab = "Frequency",
             xlab = "Number of Carburetors",
             cex.lab = 1.3,       # Sets the font of the axis labels to be larger
             main = "",           # Stops the default label from being printed
             cex.names = 1,       # Optional: size axis labels: 1 is no change.
             cex.axis = 1,        # Optional: size axis numbers.
             yaxs = "i",          # Tightens the axis to the plot.
             xaxs = "i",
             mgp = c(2.2, 0.5, 0) # Changes the margins around the plot;
                                  # see par(); c(axis title, axis labels and axis line)
)

# Restore default font
par(family = "")
```



```{r}
#| echo: false

#Set a serifed font
par(family = "serif")

# Create the barplot (histogram-like)
bp = barplot(table(carb),
            space = 0,         # Changes from a barplot to a Histogram
            col = "white",     # Leaves no bar fill for a minimalist printing
            ylab = "Frequency",
            xlab = "Number of Carburetors",
            cex.lab = 1.3,    # Sets the font of the axis labels to be larger
            main = "",        # Stops the default label from being printed
            cex.names = 1,    # Optional: size axis labels: 1 is no change.
            cex.axis = 1,     # Optional: size axis numbers.
            yaxs = 'i',       # Tightens the axis to the plot.
            xaxs = 'i',
            mgp = c(2.2, 0.5, 0)  # Changes the margins around the plot;
                                  # see par(); c(axis title, axis labels and axis line)
            
            )

#Restore default font
par(family = "")
```


```{r}
#Set a serifed font
par(family = "serif")

# Create the barplot (histogram-like)
bp = barplot(table(carb),
            space = 0,         # Changes from a barplot to a Histogram
            col = "white",     # Leaves no bar fill for a minimalist printing
            ylab = "Frequency",
            xlab = "Number of Carburetors",
            cex.lab = 1.3,    # Sets the font of the axis labels to be larger
            main = "",        # Stops the default label from being printed
            cex.names = 1,    # Optional: size axis labels: 1 is no change.
            cex.axis = 1,     # Optional: size axis numbers.
            yaxs = 'i',       # Tightens the axis to the plot.
            xaxs = 'i',
            mgp = c(2.2, 0.5, 0)  # Changes the margins around the plot;
                                  # see par(); c(axis title, axis labels and axis line)
            
            )

### Superimpose a normal curve on the current plot.

# To draw on a plot, the computer needs numbers instead of factor levels  

CarbForPlot = as.numeric(carb)

# This function looks at your plot, gets all the x values and uses those to 
# draw the normal curve.
curve(dnorm(x,
            mean = mean(CarbForPlot),
            sd = sd(CarbForPlot)) * length(CarbForPlot),
      add = T,          # Says you can add the line to an existing plot
      col = "black",    # Line color
      lwd = 2)          # Line width


#Restore default font
par(family = "")
```