---
title: "Lab 9"
format: html
execute:
   echo: false
   warning: false
   fig-dpi: 300
---


```{r}
library(tidyverse)
library(knitr)
library(car)
library(psych)
library(emmeans)
library(phia)
library(interactions)
```


```{r}
# Load your data
ReportingExampleData = read.table("3-way ANOVA Lecture.csv",
                          sep = ",",
                          header = T,
                          colClasses = c("factor",
                                         "factor",
                                         "factor",
                                         "integer"))
```

### Your data
```{r}
kable (ReportingExampleData,align = 'c')
kable (describe(ReportingExampleData)[2:4], align = 'c')
```


```{r}

# "contr.sum" is the correct option for typle type III SS
options(contrasts = c("contr.sum", "contr.poly"))
# "contr.treatment" is a reference group type contrast closer to a type I or
# type II SS.
#options(contrasts = c("contr.treatment", "contr.poly"))

leveneTest(Score ~ Kids * Vote * Politics,ReportingExampleData)
```

### Linear Model
```{r}
ReportingExANOVA = lm(Score ~ Kids * Vote * Politics, ReportingExampleData )

summary(ReportingExANOVA)

```

# Omnibus
```{r}
a = Anova(ReportingExANOVA, type = 3)
kable(a,align = 'c')
```

```{r}
# Post hoc adjustment type. Uncomment only one choice.
AdjustmentChoice = "none" # Least significant difference
# AdjustmentChoice = "bonferrroni"
# AdjustmentChoice = "tukey"
```

### Two-way comparisons

```{r}
# Cell means for Vote at each level of Kids
d <- describeBy(Score ~ Kids + Vote, data = ReportingExampleData, mat = TRUE, digits = 2)
names(d)[names(d) == "group1"] <- "Kids"
names(d)[names(d) == "group2"] <- "Vote"
rownames(d) <- NULL
d[c(2,3,5:7,16)] %>%
  kable(caption = "Descriptives: Vote at each level of Kids", align = 'c')
```

```{r}
emmeans(ReportingExANOVA, pairwise ~ Vote | Kids, adjust = AdjustmentChoice)$contrasts %>% 
  kable(caption = "Pairwise Vote at each level of Kids", align = 'c')
```

```{r}
# Cell means for Vote at each level of Politics
d <- describeBy(Score ~ Politics + Vote, data = ReportingExampleData, mat = TRUE, digits = 2)
names(d)[names(d) == "group1"] <- "Politics"
names(d)[names(d) == "group2"] <- "Vote"
rownames(d) <- NULL
d[c(2,3,5:7,16)] %>%
  kable(caption = "Descriptives: Vote at each level of Politics", align = 'c')
```

```{r}
emmeans(ReportingExANOVA, pairwise ~ Vote | Politics, adjust = AdjustmentChoice)$contrasts %>% 
  kable(caption = "Pairwise Vote at each level of Politics", align = 'c')
```

```{r}
# Cell means for Kids at each level of Politics
d <- describeBy(Score ~ Politics + Kids, data = ReportingExampleData, mat = TRUE, digits = 2)
names(d)[names(d) == "group1"] <- "Politics"
names(d)[names(d) == "group2"] <- "Kids"
rownames(d) <- NULL
d[c(2,3,5:7,16)] %>%
  kable(caption = "Descriptives: Kids at each level of Politics", align = 'c')
```

```{r}
emmeans(ReportingExANOVA, pairwise ~ Kids | Politics, adjust = AdjustmentChoice)$contrasts %>% 
  kable(caption = "Pairwise Kids at each level of Politics", align = 'c')
```

```{r}
# Cell means for Kids at each level of Vote
d <- describeBy(Score ~ Vote + Kids, data = ReportingExampleData, mat = TRUE, digits = 2)
names(d)[names(d) == "group1"] <- "Vote"
names(d)[names(d) == "group2"] <- "Kids"
rownames(d) <- NULL
d[c(2,3,5:7,16)] %>%
  kable(caption = "Descriptives: Kids at each level of Vote", align = 'c')
```

```{r}
emmeans(ReportingExANOVA, pairwise ~ Kids | Vote, adjust = AdjustmentChoice)$contrasts %>% 
  kable(caption = "Pairwise Kids at each level of Vote", align = 'c')
```

```{r}
# Cell means for Politics at each level of Kids
d <- describeBy(Score ~ Kids + Politics, data = ReportingExampleData, mat = TRUE, digits = 2)
names(d)[names(d) == "group1"] <- "Kids"
names(d)[names(d) == "group2"] <- "Politics"
rownames(d) <- NULL
d[c(2,3,5:7,16)] %>%
  kable(caption = "Descriptives: Politics at each level of Kids", align = 'c')
```

```{r}
emmeans(ReportingExANOVA, pairwise ~ Politics | Kids, adjust = AdjustmentChoice)$contrasts %>% 
  kable(caption = "Pairwise Kids at each level of Politics", align = 'c')
```

```{r}
# Cell means for Politics at each level of Vote
d <- describeBy(Score ~ Vote + Politics, data = ReportingExampleData, mat = TRUE, digits = 2)
names(d)[names(d) == "group1"] <- "Vote"
names(d)[names(d) == "group2"] <- "Politics"
rownames(d) <- NULL
d[c(2,3,5:7,16)] %>%
  kable(caption = "Descriptives: Politics at each level of Vote", align = 'c')
```

```{r}
emmeans(ReportingExANOVA, pairwise ~ Politics | Vote, adjust = AdjustmentChoice)$contrasts %>% 
  kable(caption = "Pairwise Politics at each level of Vote", align = 'c')
```


### Three-way comparisons

```{r}
# Cell means for Kids at each Vote × Politics combination
d <- describeBy(Score ~ Vote + Politics + Kids, data = ReportingExampleData, mat = TRUE, digits = 2)
names(d)[names(d) == "group1"] <- "Vote"
names(d)[names(d) == "group2"] <- "Politics"
names(d)[names(d) == "group3"] <- "Kids"
rownames(d) <- NULL
d[c(2,3,4,6:8,17)] %>%
  kable(caption = "Descriptives: Kids at each Vote × Politics combination", align = 'c')
```

```{r}
emmeans(ReportingExANOVA, pairwise ~ Kids | Vote * Politics, adjust = AdjustmentChoice)$contrasts %>%
  kable(caption = "Pairwise Kids at each Vote × Politics combination", align = 'c')
```

```{r}
# Cell means for Vote at each Kids × Politics combination
d <- describeBy(Score ~ Kids + Politics + Vote, data = ReportingExampleData, mat = TRUE, digits = 2)
names(d)[names(d) == "group1"] <- "Kids"
names(d)[names(d) == "group2"] <- "Politics"
names(d)[names(d) == "group3"] <- "Vote"
rownames(d) <- NULL
d[c(2,3,4,6:8,17)] %>%
  kable(caption = "Descriptives: Vote at each Kids × Politics combination", align = 'c')
```

```{r}
emmeans(ReportingExANOVA, pairwise ~ Vote | Kids * Politics, adjust = "none")$contrasts %>%
  kable(caption = "Pairwise Vote at each Kids × Politics combination", align = 'c')
```

```{r}
# Cell means for Politics at each Kids × Vote combination
d <- describeBy(Score ~ Kids + Vote + Politics, data = ReportingExampleData, mat = TRUE, digits = 2)
names(d)[names(d) == "group1"] <- "Kids"
names(d)[names(d) == "group2"] <- "Vote"
names(d)[names(d) == "group3"] <- "Politics"
rownames(d) <- NULL
d[c(2,3,4,6:8,17)] %>%
  kable(caption = "Descriptives: Politics at each Kids × Vote combination", align = 'c')
```

```{r}
emmeans(ReportingExANOVA, pairwise ~ Politics | Kids * Vote, adjust = "none")$contrasts %>%
  kable(caption = "Pairwise Politics at each Kids × Vote combination", align = 'c')
```
