---
title: "Lab 5"
format: html
execute:
   echo: false
   warning: false
   message: false
---

```{r}
library(knitr)
library(car)
library(emmeans)
library(effectsize)
library(psych)

```


# Power analysis for the repeated-measures (paired) t-test
### Note: with this small df (9) the textbook will give a higher power than what you see here.
```{r}
PreGroup = sleep$extra[1:10]
PostGroup = sleep$extra[11:20]
diff = PostGroup - PreGroup

# Cohen's d
d = mean(diff) / sd(diff)
d

# Power of the test just demonstrated 
power.t.test(n = 10, 
             mean(diff),
             sd = sd(diff),
             type = "paired"
             )

# Sample size needed for a future experiment (80% power)
power.t.test(power = 0.80,
             delta = mean(diff),
             sd = sd(diff),
             type = "paired"
             )


```



# Power analysis for the independent-groups t-test (equal n)
### Note: No problem with this higher df (49)
```{r}

group1 = iris[iris$Species == "setosa",]
group2 = iris[iris$Species == "versicolor",]

# Cohen's d
d = cohens_d(group1$Sepal.Length, group2$Sepal.Length)
d

# Power of the test just demonstrated
power.t.test(n = 50, 
             delta = d$Cohens_d, 
             sd = 1,
             type = "two.sample"
             )

# Sample size needed for a future experiment (80% power)
power.t.test(power = 0.80,
             delta = d$Cohens_d, 
             sd = 1,
             type = "two.sample"
             )

```


# Power analysis for the independent-groups t-test (unequal n)
```{r}

group1 = iris[iris$Species == "virginica",]
group2 = iris[iris$Species == "versicolor",][1:20,]

# Cohen's d
d = cohens_d(group1$Sepal.Width, group2$Sepal.Width)
d

# Power of the test just demonstrated (approximate with smaller n)
power.t.test(n = 20,
             delta = d$Cohens_d, 
             sd = 1,
             type = "two.sample"
             )

# Sample size needed for a future experiment (80% power)
power.t.test(power = 0.80,
             delta = d$Cohens_d, 
             sd = 1,
             type = "two.sample"
             )

```




