---
title: "Lab 4"
format: html
execute:
   echo: false
   warning: false
   message: false
---

```{r}
library(knitr)
library(car)
library(emmeans)
library(effectsize)
library(psych)

```


# Probability (p-value) of a t-score.
```{r}
t_score = .376
df = 14
Tails = 2

pt(t_score,df, lower.tail = F) * Tails

```


# Get a t-score (t-crit) from a probablity value (p-value or alpha)
```{r}

probability = .025
df = 14

qt(probability, df, lower.tail = F)


```


# Repeated-measures (paired) t-test
```{r}

PreGroup = sleep$extra[1:10]

PostGroup = sleep$extra[11:20]

describe (PreGroup)

describe (PostGroup)

diff = PostGroup - PreGroup
sd(df)

leveneTest(extra~group,sleep)

t.test(PreGroup,PostGroup, paired = TRUE)

# cohen's d
mean(diff) / sd(diff)


```

# Independent-groups t-test (equal n)
```{r}

group1 = iris[iris$Species == "setosa",]

group2 = iris[iris$Species == "versicolor",]

EqualIndependentData = rbind(group1,
                             group2
                             )

describe(group1$Sepal.Length)

describe(group2$Sepal.Length)

leveneTest(Sepal.Length ~ Species,EqualIndependentData)

t.test(group1$Sepal.Length ,group2$Sepal.Length)

# Equal group sizes should make the test robust to violations of homogeneity
# of variance. So, the following method should be acceptable.
t.test(group1$Sepal.Length, group2$Sepal.Length,
       var.equal = T)

# Explicity calculate the pooled standard deviation in order to obtain Cohen's d.
m1 = mean(group1$Sepal.Length)
m2 = mean(group2$Sepal.Length)
s1 = sd(group1$Sepal.Length)
s2 = sd(group2$Sepal.Length)
n1 = nrow(group1)
n2 = nrow(group2)

sd_pooled = sqrt( ((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2) )

sd_pooled

(m1 - m2) / sd_pooled

cohens_d(group1$Sepal.Length,group2$Sepal.Length)

```



# Independent-groups t-test (unequal n)
```{r}

group1 = iris[iris$Species == "virginica",]

group2 = iris[iris$Species == "versicolor",][1:20,]

UnequalIndependentData = rbind(group1, group2)

describe(group1$Sepal.Width)

describe(group2$Sepal.Width)

leveneTest(Sepal.Width ~ Species, UnequalIndependentData)

t.test(group1$Sepal.Width, group2$Sepal.Width)

t.test(group1$Sepal.Width, group2$Sepal.Width,
       var.equal = TRUE)

# Explicity calculate the pooled standard deviation in order to obtain Cohen's d.
m1 = mean(group1$Sepal.Width)
m2 = mean(group2$Sepal.Width)
s1 = sd(group1$Sepal.Width)
s2 = sd(group2$Sepal.Width)
n1 = nrow(group1)
n2 = nrow(group2)

sd_pooled = sqrt( ((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2) )

sd_pooled

cohens_d(group1$Sepal.Width, group2$Sepal.Width)


```
